name: himish
description: "A new Flutter project sdk version is 3.27.2"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.4
  flutter_animate: ^4.5.2
  flutter_bounce: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.17
  http: ^1.4.0
  logger: ^2.6.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.1.0
  another_flushbar: ^1.12.30
  pinput: ^5.0.0
  get: ^4.6.6
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  dartz: ^0.10.1
  dotted_border:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/bottom/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800